const ADD_CATEGORY = "ADD_CATEGORY";
const SET_CATEGORIES = "SET_CATEGORIES";
const DELETE_CATEGORY = "DELETE_CATEGORY";
const EDIT_CATEGORY = "EDIT_CATEGORY";


export { ADD_CATEGORY, SET_CATEGORIES, DELETE_CATEGORY, EDIT_CATEGORY };