const ADD_PRODUCT = "ADD_PRODUCT";
const SET_PRODUCTS = "SET_PRODUCTS";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";


export { ADD_PRODUCT, SET_PRODUCTS, DELETE_PRODUCT, EDIT_PRODUCT };