const SET_HEAD_CELLS = "SET_HEAD_CELLS";
const SET_SELECTED_NUMBERS = "SET_SELECTED_NUMBERS";
const SET_TABLE_DATA = "SET_DATA";
const SET_TABLE_TITLE = "SET_TABLE_TITLE";

export { SET_HEAD_CELLS, SET_SELECTED_NUMBERS, SET_TABLE_DATA, SET_TABLE_TITLE };