# Generated by Django 3.2.4 on 2021-06-24 23:44

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('volume', models.PositiveIntegerField(verbose_name='Объем памяти')),
                ('number_of_gamepads', models.PositiveIntegerField(default=1, verbose_name='Количество геймпадов')),
            ],
            options={
                'verbose_name': 'Консоль',
                'verbose_name_plural': 'Консоли',
                'ordering': ('name',),
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='ConsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Название')),
                ('slug', models.SlugField(max_length=25, verbose_name='Алиас')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.user_directory_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Blu-ray Disc'), (2, 'Digital copies')])),
                ('console_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='catalog.consolemodel')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ('name',),
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='Алиас')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='console',
            name='console_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consoles', to='catalog.consolemodel'),
        ),
    ]
