# Generated by Django 3.2.5 on 2021-07-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210722_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.product', verbose_name='Значение атрибута для продукта'),
            preserve_default=False,
        ),
    ]
