# Generated by Django 3.2.4 on 2021-06-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210625_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolemodel',
            options={'verbose_name': 'Модель консоли', 'verbose_name_plural': 'Модель консоли'},
        ),
    ]
