# Generated by Django 3.2.5 on 2021-08-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_attributevalue_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='inbanner',
            field=models.BooleanField(default=False, verbose_name='Показывать в баннере'),
        ),
        migrations.AddField(
            model_name='product',
            name='incarousel',
            field=models.BooleanField(default=False, verbose_name='Показывать в карусели'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='catalog.Category', verbose_name='Категория'),
        ),
    ]
